#! /usr/bin/env python
# -*- coding: UTF-8 -*-

import json
import argparse
from glob import glob

FORMAT_VERSION = "1"

def read_frame(path):
    with open(path) as f:
        return f.read()

def main(path, output="movie.go"):
    frames_source = sorted(glob("%s/*.txt" % path))
    print("Reading %d frames..." % len(frames_source))

    with open(output, "w") as f:
        f.write("package main\n\n// Generated by compile_movie.py\n")
        f.write("var frames = []string{\n")

        for source in frames_source:
            frame = read_frame(source)
            f.write("\t")
            json.dump(frame, f),
            f.write(",\n")

        f.write("}\n")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("path")
    parser.add_argument("-o", "--out", default="movie.go")
    opts = parser.parse_args()
    main(opts.path, output=opts.out)
